### ISSUE TITLE
Config change doesn't work?

### ISSUE THREAD

**Issue by quat1024** [VazkiiMods/Zeta#3]
1. cover yourself in oil
2. open q menu and change a config option
3. press save
4. 

```
java.lang.RuntimeException: Exception while firing event org.violetmoon.zeta.event.load.ZConfigChanged@298fe4f6: 
	at TRANSFORMER/zeta@1.0-13.58/org.violetmoon.zeta.event.bus.ZetaEventBus$Listeners.doFire(ZetaEventBus.java:229)
	at TRANSFORMER/zeta@1.0-13.58/org.violetmoon.zeta.event.bus.ZetaEventBus.fire(ZetaEventBus.java:103)
	at TRANSFORMER/zeta@1.0-13.58/org.violetmoon.zetaimplforge.config.ConfigEventDispatcher.handleConfigChange(ConfigEventDispatcher.java:31)
	at TRANSFORMER/zeta@1.0-13.58/org.violetmoon.zetaimplforge.config.ConfigEventDispatcher.configChanged(ConfigEventDispatcher.java:20)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at LAYER PLUGIN/javafmllanguage@1.20.1-47.1.3/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:42)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$13(ModContainer.java:153)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:153)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:77)
	at LAYER PLUGIN/fmlcore@1.20.1-47.1.3/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:147)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
Caused by: java.lang.IllegalArgumentException: Invalid message org.violetmoon.zeta.network.message.C2SUpdateFlag
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:132)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.network.simple.SimpleChannel.sendTo(SimpleChannel.java:92)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.network.simple.SimpleChannel.sendToServer(SimpleChannel.java:87)
	at TRANSFORMER/zeta@1.0-13.58/org.violetmoon.zetaimplforge.network.ForgeZetaNetworkHandler.sendToServer(ForgeZetaNetworkHandler.java:98)
	at TRANSFORMER/zeta@1.0-13.58/org.violetmoon.zeta.client.ZetaClient.sendToServer(ZetaClient.java:73)
	at TRANSFORMER/zeta@1.0-13.58/org.violetmoon.zeta.client.config.ClientConfigManager.configChanged(ClientConfigManager.java:63)
	at TRANSFORMER/zeta@1.0-13.58/org.violetmoon.zeta.event.bus.ZetaEventBus$Listeners.doFireNonCancellable(ZetaEventBus.java:242)
	at TRANSFORMER/zeta@1.0-13.58/org.violetmoon.zeta.event.bus.ZetaEventBus$Listeners.doFire(ZetaEventBus.java:227)
	... 14 more
```

**Comment by qznfbnj** [comment]
Text below be as additional information

---
I found that when using the latest Modernfix, the in-game Quark configuration changes are invalid. Of course, the error in the log also disappears.
Modernfix-5.5.0: Quark configuration can be reloaded
Modernfix-5.6.0-5.14.0: Quark configuration can still be reloaded by executing /mf(s)rc manually
Modernfix-5.15.0-5.17.0: Quark configuration cannot be reloaded even with /mf(s)rc (even if all features of Modernfix are disabled)

Then I asked in TauMC discord server and get response:

> That sounds like Zeta is relying on saving the config file and then hoping it automatically reloads, rather than actually changing the config values in memory
>
> ModernFix only controls watching the config file on disk, it shouldn't break any attempts to modify the config from the game itself, unless mods are doing weird things

**Comment by quat1024** [comment]
^ That seems like a different problem btw

**Comment by quat1024** [comment]
This still happens in singleplayer and tbh idk why. I think the config change *does* go through
