### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by fakegamingnerd** [VazkiiMods/Zeta#37]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2024-08-04 08:37:32
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.5-universal.jar%23444!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.3.5-universal.jar%23444!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23439!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mod: 
	Zeta (zeta), Version: 1.0-21
		Issue tracker URL: https://github.com/VazkiiMods/Zeta
		at TRANSFORMER/zeta@1.0-21/org.violetmoon.zeta.event.bus.ZetaEventBus.methodProblem(ZetaEventBus.java:143)
Stacktrace:
	at org.violetmoon.zeta.event.bus.ZetaEventBus.methodProblem(ZetaEventBus.java:143) ~[Zeta-1.0-21.jar%23437!/:1.0-21] {re:classloading}
-- MOD quark --
Details:
	Mod File: /home/minecraft/multicraft/servers/server2336582/profile_sqxkz/mods/Quark-4.0-459.jar
	Failure message: Quark (quark) has failed to load correctly
		java.lang.RuntimeException: Method annotated with @LoadEvent should take an implementor of IZetaLoadEvent.
		Method class: org.violetmoon.quark.content.world.module.AzaleaWoodModule
		Method name: onServerReload
	Mod Version: 4.0-459
	Mod Issue URL: https://github.com/VazkiiMods/Quark
	Exception message: java.lang.RuntimeException: Method annotated with @LoadEvent should take an implementor of IZetaLoadEvent.
Method class: org.violetmoon.quark.content.world.module.AzaleaWoodModule
Method name: onServerReload
Stacktrace:
	at org.violetmoon.zeta.event.bus.ZetaEventBus.methodProblem(ZetaEventBus.java:143) ~[Zeta-1.0-21.jar%23437!/:1.0-21] {re:classloading}
	at org.violetmoon.zeta.event.bus.ZetaEventBus.typeERR(ZetaEventBus.java:133) ~[Zeta-1.0-21.jar%23437!/:1.0-21] {re:classloading}
	at org.violetmoon.zetaimplforge.event.ForgeZetaEventBus.subscribeMethod(ForgeZetaEventBus.java:105) ~[Zeta-1.0-21.jar%23437!/:1.0-21] {re:classloading}
	at org.violetmoon.zeta.event.bus.ZetaEventBus.lambda$subscribe$0(ZetaEventBus.java:60) ~[Zeta-1.0-21.jar%23437!/:1.0-21] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at org.violetmoon.zeta.event.bus.ZetaEventBus.subscribe(ZetaEventBus.java:60) ~[Zeta-1.0-21.jar%23437!/:1.0-21] {re:classloading}
	at org.violetmoon.zeta.module.ZetaModuleManager.constructAndSetup(ZetaModuleManager.java:155) ~[Zeta-1.0-21.jar%23437!/:1.0-21] {re:classloading}
	at org.violetmoon.zeta.module.ZetaModuleManager.load(ZetaModuleManager.java:129) ~[Zeta-1.0-21.jar%23437!/:1.0-21] {re:classloading}
	at org.violetmoon.zeta.Zeta.loadModules(Zeta.java:131) ~[Zeta-1.0-21.jar%23437!/:1.0-21] {re:mixin,re:classloading}
	at org.violetmoon.quark.base.proxy.CommonProxy.start(CommonProxy.java:80) ~[Quark-4.0-459.jar%23406!/:4.0-459] {re:classloading}
	at org.violetmoon.quark.base.Quark.<init>(Quark.java:55) ~[Quark-4.0-459.jar%23406!/:4.0-459] {re:classloading,re:mixin}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.5.jar%23441!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.5.jar%23440!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
[crash-2024-08-04_08.37.32-fml.txt](https://github.com/user-attachments/files/16486949/crash-2024-08-04_08.37.32-fml.txt)

**Comment by mudgw2** [comment]
Same:

	Quark (quark) has failed to load correctly
§7java.lang.RuntimeException: Could not convert Zeta event class interface org.violetmoon.zeta.client.event.load.ZClientSetup to Forge event. You must register its subclass using registerSubclass.

**Comment by Catpoint789** [comment]
I'm getting this same error no matter what versions of Quark or Zeta I switch to. Guess it's just broken right now... thanks devs.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mod:
        Zeta (zeta), Version: 1.0-23
                Issue tracker URL: https://github.com/VazkiiMods/Zeta
                at TRANSFORMER/zeta@1.0-23/org.violetmoon.zetaimplforge.event.ForgeEventsRemapper.remapMethod(ForgeEventsRemapper.java:80)
Stacktrace:
        at org.violetmoon.zetaimplforge.event.ForgeEventsRemapper.remapMethod(ForgeEventsRemapper.java:80) ~[Zeta-1.0-23.jar%23467!/:1.0-23] {re:classloading}
-- MOD quark --
Details:
        Mod File: /C:/Users/brodi/Desktop/server/mods/Quark-4.0-460.jar
        Failure message: Quark (quark) has failed to load correctly
                java.lang.RuntimeException: Could not convert Zeta event class interface org.violetmoon.zeta.client.event.load.ZClientSetup to Forge event. You must register its subclass using registerSubclass.
        Mod Version: 4.0-460
        Mod Issue URL: https://github.com/VazkiiMods/Quark
        Exception message: java.lang.RuntimeException: Could not convert Zeta event class interface org.violetmoon.zeta.client.event.load.ZClientSetup to Forge event. You must register its subclass using registerSubclass.

**Comment by corbinpenguin** [comment]
Same here

**Comment by Catpoint789** [comment]
If you need a temporary fix while the devs sort their shit out, try downgrading Zeta and Quark. I had to go to 1.0-19 for Zeta and 4.0-458 for Quark.

**Comment by corbinpenguin** [comment]
> If you need a temporary fix while the devs sort their shit out, try downgrading Zeta and Quark. I had to go to 1.0-19 for Zeta and 4.0-458 for Quark.

My server is launching fine with Zeta 1.0-19 and Quark 4.0-459, if you did want to update quark

**Comment by silverxd3** [comment]
Downgrading Quark and Zeta to older versions like the one you recommend doesn't work for me. My server keeps crashing.

**Comment by Catpoint789** [comment]
> Downgrading Quark and Zeta to older versions like the one you recommend doesn't work for me. My server keeps crashing.

It seems to be super finicky and fragile right now. Try to keep downgrading until it works. Obviously downgrading you may lose features and that might cause problems, but like I said, just temporary. Obviously either the Quark and/or the Zeta devs fucked something up with the compatibilities. Frustrating.

**Comment by silverxd3** [comment]
nothing work :c

**Comment by fakegamingnerd** [comment]
Was fixed for me by updating quark and zeta to at time of comment latest update

**Comment by silverxd3** [comment]
It may have been fixed for the client, but not for the servers, where the problem is still present. I've been wanting to play with my friends on a modded server since yesterday, but since the problem is still present for the servers it's not possible.
