### ISSUE TITLE
Error with Zeta and Quark server side only for 1.20.1 FML

### ISSUE THREAD

**Issue by Nanocite** [VazkiiMods/Zeta#39]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-08-04 17:09:10
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.5-universal.jar%23284!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.3.5-universal.jar%23284!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23279!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mod: 
	Zeta (zeta), Version: 1.0-23
		Issue tracker URL: https://github.com/VazkiiMods/Zeta
		at TRANSFORMER/zeta@1.0-23/org.violetmoon.zetaimplforge.event.ForgeEventsRemapper.remapMethod(ForgeEventsRemapper.java:80)
Stacktrace:
	at org.violetmoon.zetaimplforge.event.ForgeEventsRemapper.remapMethod(ForgeEventsRemapper.java:80) ~[Zeta-1.0-23.jar%23277!/:1.0-23] {re:classloading}
-- MOD quark --
Details:
	Mod File: /C:/Users/Aidan/Desktop/Server/mods/Quark-4.0-460.jar
	Failure message: Quark (quark) has failed to load correctly
		java.lang.RuntimeException: Could not convert Zeta event class interface org.violetmoon.zeta.client.event.load.ZClientSetup to Forge event. You must register its subclass using registerSubclass.
	Mod Version: 4.0-460
	Mod Issue URL: https://github.com/VazkiiMods/Quark
	Exception message: java.lang.RuntimeException: Could not convert Zeta event class interface org.violetmoon.zeta.client.event.load.ZClientSetup to Forge event. You must register its subclass using registerSubclass.
Stacktrace:
	at org.violetmoon.zetaimplforge.event.ForgeEventsRemapper.remapMethod(ForgeEventsRemapper.java:80) ~[Zeta-1.0-23.jar%23277!/:1.0-23] {re:classloading}
	at org.violetmoon.zetaimplforge.event.ForgeEventsRemapper.remapAndRegister(ForgeEventsRemapper.java:375) ~[Zeta-1.0-23.jar%23277!/:1.0-23] {re:classloading}
	at org.violetmoon.zetaimplforge.event.ForgeZetaEventBus.subscribeMethod(ForgeZetaEventBus.java:85) ~[Zeta-1.0-23.jar%23277!/:1.0-23] {re:classloading}
	at org.violetmoon.zeta.event.bus.ZetaEventBus.lambda$subscribe$0(ZetaEventBus.java:60) ~[Zeta-1.0-23.jar%23277!/:1.0-23] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at org.violetmoon.zeta.event.bus.ZetaEventBus.subscribe(ZetaEventBus.java:60) ~[Zeta-1.0-23.jar%23277!/:1.0-23] {re:classloading}
	at org.violetmoon.zeta.module.ZetaModuleManager.constructAndSetup(ZetaModuleManager.java:155) ~[Zeta-1.0-23.jar%23277!/:1.0-23] {re:classloading}
	at org.violetmoon.zeta.module.ZetaModuleManager.load(ZetaModuleManager.java:129) ~[Zeta-1.0-23.jar%23277!/:1.0-23] {re:classloading}
	at org.violetmoon.zeta.Zeta.loadModules(Zeta.java:132) ~[Zeta-1.0-23.jar%23277!/:1.0-23] {re:mixin,re:classloading}
	at org.violetmoon.quark.base.proxy.CommonProxy.start(CommonProxy.java:82) ~[Quark-4.0-460.jar%23236!/:4.0-460] {re:classloading}
	at org.violetmoon.quark.base.Quark.<init>(Quark.java:55) ~[Quark-4.0-460.jar%23236!/:4.0-460] {re:classloading,re:mixin}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.5.jar%23281!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.5.jar%23280!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.12, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 149013320 bytes (142 MiB) / 524288000 bytes (500 MiB) up to 4276092928 bytes (4078 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 2700 Eight-Core Processor          
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.65
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=32.0.15.6070
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29109.61
	Virtual memory used (MB): 12849.75
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 916.45
	JVM Flags: 0 total; 
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		dynamiclightsreforged-1.20.1_v1.6.0.jar           |Rubidium Dynamic Lights       |dynamiclightsreforged         |1.20.1_v1.6.0       |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterDungeons-1.20-Forge-4.0.4.jar          |YUNG's Better Dungeons        |betterdungeons                |1.20-Forge-4.0.4    |COMMON_SET|Manifest: NOSIGNATURE
		kuma-api-forge-20.1.8+1.20.1.jar                  |KumaAPI                       |kuma_api                      |20.1.8              |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.20.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.20-Forge-3.0.3.jar         |YUNG's Better Witch Huts      |betterwitchhuts               |1.20-Forge-3.0.3    |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.4.7.jar                   |GeckoLib 4                    |geckolib                      |4.4.7               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar    |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.20-Forge-3.0.4    |COMMON_SET|Manifest: NOSIGNATURE
		Neat-1.20-35-FORGE.jar                            |Neat                          |neat                          |1.20-35-FORGE       |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.38.8_Forge_1.20.jar              |Xaero's World Map             |xaeroworldmap                 |1.38.8              |COMMON_SET|Manifest: NOSIGNATURE
		JRFTL-1.20.1-1.6.0.jar                            |JRFTL                         |jrftl                         |1.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-forge-1.20.1-12.0.2.jar               |Controlling                   |controlling                   |12.0.2              |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.20.1-8.6.2.jar                          |Placebo                       |placebo                       |8.6.2               |COMMON_SET|Manifest: NOSIGNATURE
		modernfix-forge-5.19.0+mc1.20.1.jar               |ModernFix                     |modernfix                     |5.19.0+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.5.6-1.20.1.jar                          |Citadel                       |citadel                       |2.5.6               |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.5.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.5    |COMMON_SET|Manifest: NOSIGNATURE
		MaxHealthFix-Forge-1.20.1-12.0.3.jar              |MaxHealthFix                  |maxhealthfix                  |12.0.3              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mixinextras-forge-0.3.6.jar                       |MixinExtras                   |mixinextras                   |0.3.6               |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.2.13.jar                |Bookshelf                     |bookshelf                     |20.2.13             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		u_team_core-forge-1.20.1-5.1.4.312.jar            |U Team Core                   |uteamcore                     |5.1.4.312           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		balm-forge-1.20.1-7.3.6-all.jar                   |Balm                          |balm                          |7.3.6               |COMMON_SET|Manifest: NOSIGNATURE
		SnowRealMagic-1.20.1-forge-10.4.0.jar             |Snow! Real Magic!             |snowrealmagic                 |10.4.0              |COMMON_SET|Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.2.7.jar                  |Carry On                      |carryon                       |2.1.2.7             |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.247.jar          |Just Enough Resources         |jeresources                   |1.4.0.247           |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar  |YUNG's Better Nether Fortresse|betterfortresses              |1.20-Forge-2.0.6    |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |COMMON_SET|Manifest: NOSIGNATURE
		sound-physics-remastered-forge-1.20.1-1.4.5.jar   |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.4.5        |COMMON_SET|Manifest: NOSIGNATURE
		embeddium-0.3.28+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.28+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
		durabilitytooltip-1.1.5-forge-mc1.20.jar          |Durability Tooltip            |durabilitytooltip             |1.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		xaeros_waystones_compability-1.0.jar              |Xaero's Map - Waystones Compab|w2w2                          |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		useful_backpacks-forge-1.20.1-2.0.1.124.jar       |Useful Backpacks              |usefulbackpacks               |2.0.1.124           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		YungsBridges-1.20-Forge-4.0.3.jar                 |YUNG's Bridges                |yungsbridges                  |1.20-Forge-4.0.3    |COMMON_SET|Manifest: NOSIGNATURE
		spark-1.10.53-forge.jar                           |spark                         |spark                         |1.10.53             |COMMON_SET|Manifest: NOSIGNATURE
		spartantoolkit-1.20.1-1.4.2.jar                   |Spartan Weaponry Addon Toolkit|spartantoolkit                |1.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-5.9.1+1.20.1.jar                     |Curios API                    |curios                        |5.9.1+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		GameStages-Forge-1.20.1-15.0.1.jar                |GameStages                    |gamestages                    |15.0.1              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		collective-1.20.1-7.80.jar                        |Collective                    |collective                    |7.80                |COMMON_SET|Manifest: NOSIGNATURE
		Searchables-forge-1.20.1-1.0.3.jar                |Searchables                   |searchables                   |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		oreexcavation-1.13.170.jar                        |OreExcavation                 |oreexcavation                 |1.13.170            |COMMON_SET|Manifest: NOSIGNATURE
		YungsExtras-1.20-Forge-4.0.3.jar                  |YUNG's Extras                 |yungsextras                   |1.20-Forge-4.0.3    |COMMON_SET|Manifest: NOSIGNATURE
		spartanfire-1.20.1-2.0.2.jar                      |Spartan Weaponry: Ice and Fire|spartanfire                   |2.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.20-Forge-4.0.3.jar       |YUNG's Better Strongholds     |betterstrongholds             |1.20-Forge-4.0.3    |COMMON_SET|Manifest: NOSIGNATURE
		SpartanWeaponry-1.20.1-forge-3.1.2-all.jar        |Spartan Weaponry              |spartanweaponry               |3.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |COMMON_SET|Manifest: NOSIGNATURE
		squatgrow-forge-5.3.0+mc1.20.1.jar                |Squat Grow                    |squatgrow                     |5.3.0+mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		cupboard-1.20.1-2.7.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.7          |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterEndIsland-1.20-Forge-2.0.6.jar         |YUNG's Better End Island      |betterendisland               |1.20-Forge-2.0.6    |COMMON_SET|Manifest: NOSIGNATURE
		bigger_vanilla_trees-forge-1.20-1.0.jar           |bigger_vanilla_trees-forge    |bigger_vanilla_trees          |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.7.6.jar                  |Framework                     |framework                     |0.7.6               |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		Towns-and-Towers-1.12-Fabric+Forge.jar            |Towns and Towers              |t_and_t                       |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		ScalingHealth-1.20.1-8.0.2+9.jar                  |Scaling Health                |scalinghealth                 |8.0.2+9             |COMMON_SET|Manifest: NOSIGNATURE
		Disenchanting-forge-1.20.1-2.2.4.jar              |Disenchanting                 |disenchanting                 |2.2.3               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.20-Forge-4.0.4.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.20-Forge-4.0.4    |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.20-Forge-2.0.5.jar     |YUNG's Better Jungle Temples  |betterjungletemples           |1.20-Forge-2.0.5    |COMMON_SET|Manifest: NOSIGNATURE
		Kiwi-1.20.1-forge-11.6.2.jar                      |Kiwi Library                  |kiwi                          |11.6.2              |COMMON_SET|Manifest: NOSIGNATURE
		XP From Harvest Reworked-1.20.x-1.2.4.jar         |XP From Harvest Reworked      |xpfromharvest                 |1.2.4               |COMMON_SET|Manifest: NOSIGNATURE
		treeharvester-1.20.1-9.0.jar                      |Tree Harvester                |treeharvester                 |9.0                 |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.8.2.26.jar                    |Just Enough Items             |jei                           |15.8.2.26           |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.4.jar                   |Waystones                     |waystones                     |14.1.4              |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.4.jar                  |Clumps                        |clumps                        |12.0.0.4            |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-6.4.0+1.20.1.jar                   |Comforts                      |comforts                      |6.4.0+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		configured-forge-1.20.1-2.2.3.jar                 |Configured                    |configured                    |2.2.3               |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		zaynens_string_from_wool_mod_1.20.1.jar           |String From Wool              |string_from_wool              |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		snowundertrees-1.20.1-1.4.4.jar                   |Snow Under Trees              |snowundertrees                |1.4.4               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.20-Forge-3.0.3.jar     |YUNG's Better Desert Temples  |betterdeserttemples           |1.20-Forge-3.0.3    |COMMON_SET|Manifest: NOSIGNATURE
		iceandfire-2.1.13-1.20.1-beta-4.jar               |Ice and Fire                  |iceandfire                    |2.1.13-1.20.1-beta-4|COMMON_SET|Manifest: NOSIGNATURE
		farsight-1.20.1-3.7.jar                           |Farsight mod                  |farsight_view                 |1.20.1-3.7          |COMMON_SET|Manifest: NOSIGNATURE
		Terralith_1.20.x_v2.5.4.jar                       |Terralith                     |terralith                     |2.5.4               |COMMON_SET|Manifest: NOSIGNATURE
		CraftTweaker-forge-1.20.1-14.0.40.jar             |CraftTweaker                  |crafttweaker                  |14.0.40             |COMMON_SET|Manifest: NOSIGNATURE
		skinlayers3d-forge-1.6.6-mc1.20.1.jar             |3d-Skin-Layers                |skinlayers3d                  |1.6.6               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.3.5-universal.jar                 |Forge                         |forge                         |47.3.5              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		RecipeStages-8.0.0.2.jar                          |Recipe Stages                 |recipestages                  |8.0.0.2             |COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.20.x-2.1.58-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.58-1.20.x       |COMMON_SET|Manifest: NOSIGNATURE
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
		DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar   |Distant Horizons              |distanthorizons               |2.1.2-a             |COMMON_SET|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.20.1-17.0.16.jar  |EnchantmentDescriptions       |enchdesc                      |17.0.16             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.20.1-3.0.1.7.jar             |TerraBlender                  |terrablender                  |3.0.1.7             |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.20-2.12.9-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.12.9         |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.20.1-2.25.1.jar             |Mouse Tweaks                  |mousetweaks                   |2.25.1              |COMMON_SET|Manifest: NOSIGNATURE
		ToolBelt-1.20.1-1.20.01.jar                       |Tool Belt                     |toolbelt                      |1.20.01             |COMMON_SET|Manifest: NOSIGNATURE
		Female-Gender-Mod-forge-1.20.1-3.0.1.jar          |Wildfire's Female Gender Mod  |wildfire_gender               |1.20.1-3.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		silent-lib-1.20.1-8.0.0.jar                       |Silent Lib                    |silentlib                     |8.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		cleanswing-1.20-1.5.jar                           |Clean Swing Through Grass     |cleanswing                    |1.20-1.5            |COMMON_SET|Manifest: NOSIGNATURE
		spectrelib-forge-0.13.15+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.15+1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		SpartanShields-1.20.1-forge-3.1.1.jar             |Spartan Shields               |spartanshields                |3.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_24.2.0_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |24.2.0              |COMMON_SET|Manifest: NOSIGNATURE
		FastWorkbench-1.20.1-8.0.4.jar                    |Fast Workbench                |fastbench                     |8.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		Zeta-1.0-23.jar                                   |Zeta                          |zeta                          |1.0-23              |COMMON_SET|Manifest: NOSIGNATURE
		Quark-4.0-460.jar                                 |Quark                         |quark                         |4.0-460             |ERROR     |Manifest: NOSIGNATURE
		inventoryhud.forge.1.20.1-3.4.24.jar              |Inventory HUD+                |inventoryhud                  |3.4.24              |COMMON_SET|Manifest: NOSIGNATURE
		betterarcheology-1.1.9-1.20.1.jar                 |Better Archeology             |betterarcheology              |1.1.9-1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		FastFurnace-1.20.1-8.0.2.jar                      |FastFurnace                   |fastfurnace                   |8.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		Aquaculture-1.20.1-2.5.2.jar                      |Aquaculture 2                 |aquaculture                   |2.5.2               |COMMON_SET|Manifest: NOSIGNATURE
		cristellib-1.1.5-forge.jar                        |Cristel Lib                   |cristellib                    |1.1.5               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 2bbb5a42-683d-4912-9574-7ad1d5f0a044
	FML: 47.3
	Forge: net.minecraftforge:47.3.5

**Comment by VPAMCreate** [comment]
I have the same error... Is there any way to fix it?

**Comment by avery1227** [comment]
I'm having the same error.

**Comment by quat1024** [comment]
Should be fixed in Quark 461 and Zeta 28 https://forum.violetmoon.org/d/453-quark-40-461-and-zeta-10-28-for-minecraft-forge-1201
